service:
  name: "go.micro.service.Order"
  version: "latest"
  listen: ":9000"
  max_qps: 200
database: 
  host: "192.168.0.62"
  port: 3306
  user: "order"
  password: "BPp6amd0i9vT3I8qrKCApQ"
  database: "orders"
  loc: "Asia/Shanghai"
  charset: "utf8mb4"
consul:
  addr: "192.168.0.62"
  port: 8500
  prefix: "/micro/"
  timeout: 180
  register_interval: 15
  register_ttl: 30
  registry_addrs: 
    - "http://192.168.0.62:8500"