apiVersion: v1
kind: ConfigMap
metadata: 
  name: crictl-config
  namespace: kube-system
data: 
  crictl.yaml: |
    runtime-endpoint: unix:///var/run/containerd/containerd.sock
    image-endpoint: unix:///var/run/containerd/containerd.sock
    timeout: 10
    debug: false
    pull-image-on-create: false
    disable-pull-on-run: false