apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ""
  name: kubernetes
contexts:
- name: jenkins-deploy-context
  context: 
    cluster: kubernetes
    user: jenkins-deployer
    namespace: dev
current-context: jenkins-deploy-context
kind: Config
users:
- name: jenkins-deployer
  user:
    token: ""

