# Default values for dtm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# DTM configuration. Specify content for config.yaml
# ref: https://github.com/dtm-labs/dtm/blob/main/conf.sample.yml
configuration: |-
  Store: 
    Driver: mysql
    Host: <host>
    User: dtmdev
    Password: <password>
    Port: 3306
    Db: dtm
    MaxOpenConns: 5
    MaxIdleConns: 200
    ConnMaxLifeTime: 5
    TransCronInterval: 3
    TimeoutToFail: 30
    RetryInterval: 10
    RequestTimeout: 2
  LogLevel: 'info'
  Log: 
    Outputs: 'stderr'
    RotationEnable: 0
    RotationConfigJSON: '{"maxsize": 100, "maxage": 0, "maxbackups": 0, "localtime": true, "compress": true}'

# replicaCount Number of dtm replicas to deploy
replicaCount: 1

# dtm image version
image:
  repository: yedf/dtm
  tag: "1.19"
  pullPolicy: IfNotPresent

# podSecurityContext: {}
  # fsGroup: 2000

# securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits: 
    cpu: 800m
    memory: 900Mi

# nodeSelector: {}

# tolerations: []

affinity: 
  podAntiAffinity: 
      preferredDuringSchedulingIgnoredDuringExecution: 
      - weight: 100
        podAffinityTerm: 
          labelSelector: 
            matchExpressions: 
            - key: app.kubernetes.io/name
              operator: In
              values: 
              - dtm
          topologyKey: "kubernetes.io/hostname"

service:
  type: ClusterIP
  ports:
    http: 36789
    grpc: 36790

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

ingress:
  enabled: false
  className: "nginx"
  annotations:
    # {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: your-domain.com
      paths:
        - path: /
          pathType: Prefix
  # tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - your-domain.com